
SCHEMA_NAME = 'shopify_littledata_prod'

# select
#     column_name
#     , data_type
#     , count(*) as ct
# from information_schema.columns
# where table_schema = 'shopify_littledata_prod'
# group by 1, 2;
segment_column_names = [
    '_id',
    'accepts_marketing',
    'action_source',
    'address_city',
    'address_country',
    'address_postal_code',
    'address_state',
    'address_street',
    'affiliation',
    'anonymous_id',
    'brand',
    'cart_id',
    'category',
    'checkout_id',
    'compare_at_price',
    'context_campaign_content',
    'context_campaign_medium',
    'context_campaign_name',
    'context_campaign_source',
    'context_external_ids',
    'context_google_analytics_client_id',
    'context_google_analytics_geoid',
    'context_integration_name',
    'context_integration_version',
    'context_ip',
    'context_library_name',
    'context_library_version',
    'context_locale',
    'context_page_path',
    'context_page_referrer',
    'context_page_search',
    'context_page_title',
    'context_page_url',
    'context_traits_default_address_city',
    'context_traits_default_address_country',
    'context_traits_default_address_postal_code',
    'context_traits_default_address_state',
    'context_traits_default_address_street',
    'context_traits_email',
    'context_traits_phone',
    'context_user_agent',
    'coupon',
    'coupon_id',
    'created_at',
    'currency',
    'customer_lifetime_value',
    'default_address_city',
    'default_address_country',
    'default_address_postal_code',
    'default_address_state',
    'default_address_street',
    'discount',
    'email',
    'event',
    'event_text',
    'fbc',
    'fbp',
    'first_name',
    'id',
    'image_url',
    'last_name',
    'list_id',
    'marketing_opt_in',
    'name',
    'order_id',
    'original_timestamp',
    'path',
    'payment_method',
    'phone',
    'position',
    'presentment_amount',
    'presentment_currency',
    'presentment_total',
    'previous_id',
    'price',
    'product_id',
    'products',
    'properties_action_source',
    'properties_brand',
    'properties_cart_id',
    'properties_category',
    'properties_compare_at_price',
    'properties_currency',
    'properties_email',
    'properties_image_url',
    'properties_name',
    'properties_presentment_amount',
    'properties_presentment_currency',
    'properties_price',
    'properties_product_id',
    'properties_products',
    'properties_quantity',
    'properties_sent_from',
    'properties_shopify_product_id',
    'properties_shopify_variant_id',
    'properties_url',
    'properties_variant',
    'purchase_count',
    'quantity',
    'query',
    'received_at',
    'referree_email',
    'referrer',
    'refund_reason',
    'results',
    'revenue',
    'search',
    'selling_plan',
    'sent_at',
    'sent_from',
    'shipping',
    'shipping_method',
    'shopify_product_id',
    'shopify_variant_id',
    'sku',
    'source_name',
    'state',
    'step',
    'subtotal',
    'tags',
    'tax',
    'timestamp',
    'title',
    'total',
    'type',
    'url',
    'user_id',
    'uuid',
    'uuid_ts',
    'variant',
    'verified_email',
]

# select distinct table_name
# from information_schema.columns
# where table_schema = 'shopify_littledata_prod';
segment_table_names = [
    'baby_on_the_way_join',
    'cart_viewed',
    'checkout_started',
    'checkout_step_completed',
    'checkout_step_viewed',
    'coupon_applied',
    'current_parent_header_button',
    'customer_created',
    'customer_enabled',
    'df',
    'expectant_parent_header_button',
    'join_current_parent_pressed',
    'join_expectant_parent_pressed',
    'membership_added_to_cart',
    'order_completed',
    'order_refunded',
    'pages',
    'payment_failure',
    'payment_info_entered',
    'product_added',
    'product_added2',
    'product_added3',
    'product_added4',
    'product_clicked',
    'product_image_clicked',
    'product_list_viewed',
    'product_removed',
    'product_viewed',
    'products_searched',
    'referral_form_submitted',
    'referral_non_logged_in',
    'registration_viewed',
    'thankyou_page_viewed'
]

# select distinct table_name, column_name
# from information_schema.columns
# where table_schema = 'shopify_littledata_prod';
segment_table_column_pairs = [
    ('aliases', 'context_library_name'),
    ('aliases', 'context_library_version'),
    ('aliases', 'id'),
    ('aliases', 'original_timestamp'),
    ('aliases', 'previous_id'),
    ('aliases', 'received_at'),
    ('aliases', 'sent_at'),
    ('aliases', 'timestamp'),
    ('aliases', 'user_id'),
    ('aliases', 'uuid'),
    ('aliases', 'uuid_ts'),
    ('baby_on_the_way_join', 'anonymous_id'),
    ('baby_on_the_way_join', 'context_google_analytics_client_id'),
    ('baby_on_the_way_join', 'context_ip'),
    ('baby_on_the_way_join', 'context_library_name'),
    ('baby_on_the_way_join', 'context_library_version'),
    ('baby_on_the_way_join', 'context_locale'),
    ('baby_on_the_way_join', 'context_page_path'),
    ('baby_on_the_way_join', 'context_page_search'),
    ('baby_on_the_way_join', 'context_page_title'),
    ('baby_on_the_way_join', 'context_page_url'),
    ('baby_on_the_way_join', 'context_user_agent'),
    ('baby_on_the_way_join', 'event'),
    ('baby_on_the_way_join', 'event_text'),
    ('baby_on_the_way_join', 'id'),
    ('baby_on_the_way_join', 'original_timestamp'),
    ('baby_on_the_way_join', 'received_at'),
    ('baby_on_the_way_join', 'sent_at'),
    ('baby_on_the_way_join', 'timestamp'),
    ('baby_on_the_way_join', 'uuid'),
    ('baby_on_the_way_join', 'uuid_ts'),
    ('cart_viewed', 'anonymous_id'),
    ('cart_viewed', 'category'),
    ('cart_viewed', 'context_google_analytics_client_id'),
    ('cart_viewed', 'context_integration_name'),
    ('cart_viewed', 'context_integration_version'),
    ('cart_viewed', 'context_ip'),
    ('cart_viewed', 'context_library_name'),
    ('cart_viewed', 'context_library_version'),
    ('cart_viewed', 'context_locale'),
    ('cart_viewed', 'context_page_path'),
    ('cart_viewed', 'context_page_referrer'),
    ('cart_viewed', 'context_page_title'),
    ('cart_viewed', 'context_page_url'),
    ('cart_viewed', 'context_user_agent'),
    ('cart_viewed', 'event'),
    ('cart_viewed', 'event_text'),
    ('cart_viewed', 'id'),
    ('cart_viewed', 'original_timestamp'),
    ('cart_viewed', 'received_at'),
    ('cart_viewed', 'sent_at'),
    ('cart_viewed', 'sent_from'),
    ('cart_viewed', 'timestamp'),
    ('cart_viewed', 'user_id'),
    ('cart_viewed', 'uuid'),
    ('cart_viewed', 'uuid_ts'),
    ('checkout_started', 'action_source'),
    ('checkout_started', 'anonymous_id'),
    ('checkout_started', 'cart_id'),
    ('checkout_started', 'category'),
    ('checkout_started', 'checkout_id'),
    ('checkout_started', 'context_google_analytics_client_id'),
    ('checkout_started', 'context_integration_name'),
    ('checkout_started', 'context_integration_version'),
    ('checkout_started', 'context_ip'),
    ('checkout_started', 'context_library_name'),
    ('checkout_started', 'context_library_version'),
    ('checkout_started', 'coupon'),
    ('checkout_started', 'currency'),
    ('checkout_started', 'discount'),
    ('checkout_started', 'email'),
    ('checkout_started', 'event'),
    ('checkout_started', 'event_text'),
    ('checkout_started', 'fbc'),
    ('checkout_started', 'fbp'),
    ('checkout_started', 'id'),
    ('checkout_started', 'original_timestamp'),
    ('checkout_started', 'presentment_currency'),
    ('checkout_started', 'products'),
    ('checkout_started', 'received_at'),
    ('checkout_started', 'sent_at'),
    ('checkout_started', 'sent_from'),
    ('checkout_started', 'source_name'),
    ('checkout_started', 'step'),
    ('checkout_started', 'timestamp'),
    ('checkout_started', 'user_id'),
    ('checkout_started', 'uuid'),
    ('checkout_started', 'uuid_ts'),
    ('checkout_step_completed', 'action_source'),
    ('checkout_step_completed', 'anonymous_id'),
    ('checkout_step_completed', 'cart_id'),
    ('checkout_step_completed', 'category'),
    ('checkout_step_completed', 'checkout_id'),
    ('checkout_step_completed', 'context_external_ids'),
    ('checkout_step_completed', 'context_google_analytics_client_id'),
    ('checkout_step_completed', 'context_google_analytics_geoid'),
    ('checkout_step_completed', 'context_integration_name'),
    ('checkout_step_completed', 'context_integration_version'),
    ('checkout_step_completed', 'context_ip'),
    ('checkout_step_completed', 'context_library_name'),
    ('checkout_step_completed', 'context_library_version'),
    ('checkout_step_completed', 'coupon'),
    ('checkout_step_completed', 'currency'),
    ('checkout_step_completed', 'discount'),
    ('checkout_step_completed', 'email'),
    ('checkout_step_completed', 'event'),
    ('checkout_step_completed', 'event_text'),
    ('checkout_step_completed', 'fbc'),
    ('checkout_step_completed', 'fbp'),
    ('checkout_step_completed', 'id'),
    ('checkout_step_completed', 'original_timestamp'),
    ('checkout_step_completed', 'presentment_currency'),
    ('checkout_step_completed', 'products'),
    ('checkout_step_completed', 'received_at'),
    ('checkout_step_completed', 'sent_at'),
    ('checkout_step_completed', 'sent_from'),
    ('checkout_step_completed', 'shipping_method'),
    ('checkout_step_completed', 'source_name'),
    ('checkout_step_completed', 'step'),
    ('checkout_step_completed', 'timestamp'),
    ('checkout_step_completed', 'user_id'),
    ('checkout_step_completed', 'uuid'),
    ('checkout_step_completed', 'uuid_ts'),
    ('checkout_step_viewed', 'action_source'),
    ('checkout_step_viewed', 'anonymous_id'),
    ('checkout_step_viewed', 'cart_id'),
    ('checkout_step_viewed', 'category'),
    ('checkout_step_viewed', 'checkout_id'),
    ('checkout_step_viewed', 'context_external_ids'),
    ('checkout_step_viewed', 'context_google_analytics_client_id'),
    ('checkout_step_viewed', 'context_google_analytics_geoid'),
    ('checkout_step_viewed', 'context_integration_name'),
    ('checkout_step_viewed', 'context_integration_version'),
    ('checkout_step_viewed', 'context_ip'),
    ('checkout_step_viewed', 'context_library_name'),
    ('checkout_step_viewed', 'context_library_version'),
    ('checkout_step_viewed', 'coupon'),
    ('checkout_step_viewed', 'currency'),
    ('checkout_step_viewed', 'discount'),
    ('checkout_step_viewed', 'email'),
    ('checkout_step_viewed', 'event'),
    ('checkout_step_viewed', 'event_text'),
    ('checkout_step_viewed', 'fbc'),
    ('checkout_step_viewed', 'fbp'),
    ('checkout_step_viewed', 'id'),
    ('checkout_step_viewed', 'original_timestamp'),
    ('checkout_step_viewed', 'payment_method'),
    ('checkout_step_viewed', 'presentment_currency'),
    ('checkout_step_viewed', 'products'),
    ('checkout_step_viewed', 'received_at'),
    ('checkout_step_viewed', 'sent_at'),
    ('checkout_step_viewed', 'sent_from'),
    ('checkout_step_viewed', 'shipping_method'),
    ('checkout_step_viewed', 'source_name'),
    ('checkout_step_viewed', 'step'),
    ('checkout_step_viewed', 'timestamp'),
    ('checkout_step_viewed', 'user_id'),
    ('checkout_step_viewed', 'uuid'),
    ('checkout_step_viewed', 'uuid_ts'),
    ('coupon_applied', 'anonymous_id'),
    ('coupon_applied', 'cart_id'),
    ('coupon_applied', 'category'),
    ('coupon_applied', 'context_google_analytics_client_id'),
    ('coupon_applied', 'context_google_analytics_geoid'),
    ('coupon_applied', 'context_library_name'),
    ('coupon_applied', 'context_library_version'),
    ('coupon_applied', 'coupon_id'),
    ('coupon_applied', 'event'),
    ('coupon_applied', 'event_text'),
    ('coupon_applied', 'id'),
    ('coupon_applied', 'original_timestamp'),
    ('coupon_applied', 'received_at'),
    ('coupon_applied', 'sent_at'),
    ('coupon_applied', 'timestamp'),
    ('coupon_applied', 'uuid'),
    ('coupon_applied', 'uuid_ts'),
    ('current_parent_header_button', 'anonymous_id'),
    ('current_parent_header_button', 'context_google_analytics_client_id'),
    ('current_parent_header_button', 'context_ip'),
    ('current_parent_header_button', 'context_library_name'),
    ('current_parent_header_button', 'context_library_version'),
    ('current_parent_header_button', 'context_locale'),
    ('current_parent_header_button', 'context_page_path'),
    ('current_parent_header_button', 'context_page_search'),
    ('current_parent_header_button', 'context_page_title'),
    ('current_parent_header_button', 'context_page_url'),
    ('current_parent_header_button', 'context_user_agent'),
    ('current_parent_header_button', 'event'),
    ('current_parent_header_button', 'event_text'),
    ('current_parent_header_button', 'id'),
    ('current_parent_header_button', 'original_timestamp'),
    ('current_parent_header_button', 'received_at'),
    ('current_parent_header_button', 'sent_at'),
    ('current_parent_header_button', 'timestamp'),
    ('current_parent_header_button', 'uuid'),
    ('current_parent_header_button', 'uuid_ts'),
    ('customer_created', '_id'),
    ('customer_created', 'accepts_marketing'),
    ('customer_created', 'anonymous_id'),
    ('customer_created', 'category'),
    ('customer_created', 'context_google_analytics_client_id'),
    ('customer_created', 'context_integration_name'),
    ('customer_created', 'context_integration_version'),
    ('customer_created', 'context_library_name'),
    ('customer_created', 'context_library_version'),
    ('customer_created', 'created_at'),
    ('customer_created', 'customer_lifetime_value'),
    ('customer_created', 'email'),
    ('customer_created', 'event'),
    ('customer_created', 'event_text'),
    ('customer_created', 'first_name'),
    ('customer_created', 'id'),
    ('customer_created', 'last_name'),
    ('customer_created', 'marketing_opt_in'),
    ('customer_created', 'original_timestamp'),
    ('customer_created', 'purchase_count'),
    ('customer_created', 'received_at'),
    ('customer_created', 'sent_at'),
    ('customer_created', 'sent_from'),
    ('customer_created', 'state'),
    ('customer_created', 'timestamp'),
    ('customer_created', 'user_id'),
    ('customer_created', 'uuid'),
    ('customer_created', 'uuid_ts'),
    ('customer_created', 'verified_email'),
    ('customer_enabled', '_id'),
    ('customer_enabled', 'accepts_marketing'),
    ('customer_enabled', 'category'),
    ('customer_enabled', 'context_google_analytics_client_id'),
    ('customer_enabled', 'context_integration_name'),
    ('customer_enabled', 'context_integration_version'),
    ('customer_enabled', 'context_library_name'),
    ('customer_enabled', 'context_library_version'),
    ('customer_enabled', 'created_at'),
    ('customer_enabled', 'customer_lifetime_value'),
    ('customer_enabled', 'default_address_city'),
    ('customer_enabled', 'default_address_country'),
    ('customer_enabled', 'default_address_postal_code'),
    ('customer_enabled', 'default_address_state'),
    ('customer_enabled', 'default_address_street'),
    ('customer_enabled', 'email'),
    ('customer_enabled', 'event'),
    ('customer_enabled', 'event_text'),
    ('customer_enabled', 'first_name'),
    ('customer_enabled', 'id'),
    ('customer_enabled', 'last_name'),
    ('customer_enabled', 'marketing_opt_in'),
    ('customer_enabled', 'original_timestamp'),
    ('customer_enabled', 'phone'),
    ('customer_enabled', 'purchase_count'),
    ('customer_enabled', 'received_at'),
    ('customer_enabled', 'sent_at'),
    ('customer_enabled', 'sent_from'),
    ('customer_enabled', 'state'),
    ('customer_enabled', 'tags'),
    ('customer_enabled', 'timestamp'),
    ('customer_enabled', 'user_id'),
    ('customer_enabled', 'uuid'),
    ('customer_enabled', 'uuid_ts'),
    ('customer_enabled', 'verified_email'),
    ('df', 'anonymous_id'),
    ('df', 'context_google_analytics_client_id'),
    ('df', 'context_ip'),
    ('df', 'context_library_name'),
    ('df', 'context_library_version'),
    ('df', 'context_locale'),
    ('df', 'context_page_path'),
    ('df', 'context_page_search'),
    ('df', 'context_page_title'),
    ('df', 'context_page_url'),
    ('df', 'context_user_agent'),
    ('df', 'event'),
    ('df', 'event_text'),
    ('df', 'id'),
    ('df', 'original_timestamp'),
    ('df', 'received_at'),
    ('df', 'sent_at'),
    ('df', 'timestamp'),
    ('df', 'uuid'),
    ('df', 'uuid_ts'),
    ('expectant_parent_header_button', 'anonymous_id'),
    ('expectant_parent_header_button', 'context_google_analytics_client_id'),
    ('expectant_parent_header_button', 'context_ip'),
    ('expectant_parent_header_button', 'context_library_name'),
    ('expectant_parent_header_button', 'context_library_version'),
    ('expectant_parent_header_button', 'context_locale'),
    ('expectant_parent_header_button', 'context_page_path'),
    ('expectant_parent_header_button', 'context_page_search'),
    ('expectant_parent_header_button', 'context_page_title'),
    ('expectant_parent_header_button', 'context_page_url'),
    ('expectant_parent_header_button', 'context_user_agent'),
    ('expectant_parent_header_button', 'event'),
    ('expectant_parent_header_button', 'event_text'),
    ('expectant_parent_header_button', 'id'),
    ('expectant_parent_header_button', 'original_timestamp'),
    ('expectant_parent_header_button', 'received_at'),
    ('expectant_parent_header_button', 'sent_at'),
    ('expectant_parent_header_button', 'timestamp'),
    ('expectant_parent_header_button', 'uuid'),
    ('expectant_parent_header_button', 'uuid_ts'),
    ('identifies', '_id'),
    ('identifies', 'accepts_marketing'),
    ('identifies', 'anonymous_id'),
    ('identifies', 'context_campaign_content'),
    ('identifies', 'context_campaign_medium'),
    ('identifies', 'context_campaign_source'),
    ('identifies', 'context_google_analytics_client_id'),
    ('identifies', 'context_ip'),
    ('identifies', 'context_library_name'),
    ('identifies', 'context_library_version'),
    ('identifies', 'context_locale'),
    ('identifies', 'context_page_path'),
    ('identifies', 'context_page_referrer'),
    ('identifies', 'context_page_search'),
    ('identifies', 'context_page_title'),
    ('identifies', 'context_page_url'),
    ('identifies', 'context_user_agent'),
    ('identifies', 'created_at'),
    ('identifies', 'customer_lifetime_value'),
    ('identifies', 'default_address_city'),
    ('identifies', 'default_address_country'),
    ('identifies', 'default_address_postal_code'),
    ('identifies', 'default_address_state'),
    ('identifies', 'default_address_street'),
    ('identifies', 'email'),
    ('identifies', 'first_name'),
    ('identifies', 'id'),
    ('identifies', 'last_name'),
    ('identifies', 'marketing_opt_in'),
    ('identifies', 'original_timestamp'),
    ('identifies', 'phone'),
    ('identifies', 'presentment_currency'),
    ('identifies', 'purchase_count'),
    ('identifies', 'received_at'),
    ('identifies', 'sent_at'),
    ('identifies', 'state'),
    ('identifies', 'tags'),
    ('identifies', 'timestamp'),
    ('identifies', 'user_id'),
    ('identifies', 'uuid'),
    ('identifies', 'uuid_ts'),
    ('identifies', 'verified_email'),
    ('join_current_parent_pressed', 'anonymous_id'),
    ('join_current_parent_pressed', 'context_google_analytics_client_id'),
    ('join_current_parent_pressed', 'context_ip'),
    ('join_current_parent_pressed', 'context_library_name'),
    ('join_current_parent_pressed', 'context_library_version'),
    ('join_current_parent_pressed', 'context_locale'),
    ('join_current_parent_pressed', 'context_page_path'),
    ('join_current_parent_pressed', 'context_page_search'),
    ('join_current_parent_pressed', 'context_page_title'),
    ('join_current_parent_pressed', 'context_page_url'),
    ('join_current_parent_pressed', 'context_user_agent'),
    ('join_current_parent_pressed', 'event'),
    ('join_current_parent_pressed', 'event_text'),
    ('join_current_parent_pressed', 'id'),
    ('join_current_parent_pressed', 'original_timestamp'),
    ('join_current_parent_pressed', 'received_at'),
    ('join_current_parent_pressed', 'sent_at'),
    ('join_current_parent_pressed', 'timestamp'),
    ('join_current_parent_pressed', 'uuid'),
    ('join_current_parent_pressed', 'uuid_ts'),
    ('join_expectant_parent_pressed', 'anonymous_id'),
    ('join_expectant_parent_pressed', 'context_google_analytics_client_id'),
    ('join_expectant_parent_pressed', 'context_ip'),
    ('join_expectant_parent_pressed', 'context_library_name'),
    ('join_expectant_parent_pressed', 'context_library_version'),
    ('join_expectant_parent_pressed', 'context_locale'),
    ('join_expectant_parent_pressed', 'context_page_path'),
    ('join_expectant_parent_pressed', 'context_page_title'),
    ('join_expectant_parent_pressed', 'context_page_url'),
    ('join_expectant_parent_pressed', 'context_user_agent'),
    ('join_expectant_parent_pressed', 'event'),
    ('join_expectant_parent_pressed', 'event_text'),
    ('join_expectant_parent_pressed', 'id'),
    ('join_expectant_parent_pressed', 'original_timestamp'),
    ('join_expectant_parent_pressed', 'received_at'),
    ('join_expectant_parent_pressed', 'sent_at'),
    ('join_expectant_parent_pressed', 'timestamp'),
    ('join_expectant_parent_pressed', 'uuid'),
    ('join_expectant_parent_pressed', 'uuid_ts'),
    ('membership_added_to_cart', '_id'),
    ('membership_added_to_cart', 'anonymous_id'),
    ('membership_added_to_cart', 'context_campaign_medium'),
    ('membership_added_to_cart', 'context_campaign_name'),
    ('membership_added_to_cart', 'context_campaign_source'),
    ('membership_added_to_cart', 'context_google_analytics_client_id'),
    ('membership_added_to_cart', 'context_ip'),
    ('membership_added_to_cart', 'context_library_name'),
    ('membership_added_to_cart', 'context_library_version'),
    ('membership_added_to_cart', 'context_locale'),
    ('membership_added_to_cart', 'context_page_path'),
    ('membership_added_to_cart', 'context_page_referrer'),
    ('membership_added_to_cart', 'context_page_search'),
    ('membership_added_to_cart', 'context_page_title'),
    ('membership_added_to_cart', 'context_page_url'),
    ('membership_added_to_cart', 'context_user_agent'),
    ('membership_added_to_cart', 'email'),
    ('membership_added_to_cart', 'event'),
    ('membership_added_to_cart', 'event_text'),
    ('membership_added_to_cart', 'id'),
    ('membership_added_to_cart', 'original_timestamp'),
    ('membership_added_to_cart', 'quantity'),
    ('membership_added_to_cart', 'received_at'),
    ('membership_added_to_cart', 'selling_plan'),
    ('membership_added_to_cart', 'sent_at'),
    ('membership_added_to_cart', 'timestamp'),
    ('membership_added_to_cart', 'type'),
    ('membership_added_to_cart', 'user_id'),
    ('membership_added_to_cart', 'uuid'),
    ('membership_added_to_cart', 'uuid_ts'),
    ('order_completed', 'action_source'),
    ('order_completed', 'affiliation'),
    ('order_completed', 'anonymous_id'),
    ('order_completed', 'cart_id'),
    ('order_completed', 'category'),
    ('order_completed', 'checkout_id'),
    ('order_completed', 'context_external_ids'),
    ('order_completed', 'context_google_analytics_client_id'),
    ('order_completed', 'context_google_analytics_geoid'),
    ('order_completed', 'context_integration_name'),
    ('order_completed', 'context_integration_version'),
    ('order_completed', 'context_ip'),
    ('order_completed', 'context_library_name'),
    ('order_completed', 'context_library_version'),
    ('order_completed', 'coupon'),
    ('order_completed', 'currency'),
    ('order_completed', 'discount'),
    ('order_completed', 'email'),
    ('order_completed', 'event'),
    ('order_completed', 'event_text'),
    ('order_completed', 'fbp'),
    ('order_completed', 'id'),
    ('order_completed', 'order_id'),
    ('order_completed', 'original_timestamp'),
    ('order_completed', 'presentment_amount'),
    ('order_completed', 'presentment_currency'),
    ('order_completed', 'products'),
    ('order_completed', 'received_at'),
    ('order_completed', 'sent_at'),
    ('order_completed', 'sent_from'),
    ('order_completed', 'shipping'),
    ('order_completed', 'source_name'),
    ('order_completed', 'subtotal'),
    ('order_completed', 'tax'),
    ('order_completed', 'timestamp'),
    ('order_completed', 'total'),
    ('order_completed', 'user_id'),
    ('order_completed', 'uuid'),
    ('order_completed', 'uuid_ts'),
    ('order_refunded', 'action_source'),
    ('order_refunded', 'anonymous_id'),
    ('order_refunded', 'category'),
    ('order_refunded', 'checkout_id'),
    ('order_refunded', 'context_external_ids'),
    ('order_refunded', 'context_google_analytics_client_id'),
    ('order_refunded', 'context_google_analytics_geoid'),
    ('order_refunded', 'context_integration_name'),
    ('order_refunded', 'context_integration_version'),
    ('order_refunded', 'context_library_name'),
    ('order_refunded', 'context_library_version'),
    ('order_refunded', 'currency'),
    ('order_refunded', 'email'),
    ('order_refunded', 'event'),
    ('order_refunded', 'event_text'),
    ('order_refunded', 'id'),
    ('order_refunded', 'order_id'),
    ('order_refunded', 'original_timestamp'),
    ('order_refunded', 'presentment_amount'),
    ('order_refunded', 'presentment_currency'),
    ('order_refunded', 'products'),
    ('order_refunded', 'received_at'),
    ('order_refunded', 'refund_reason'),
    ('order_refunded', 'revenue'),
    ('order_refunded', 'sent_at'),
    ('order_refunded', 'sent_from'),
    ('order_refunded', 'source_name'),
    ('order_refunded', 'timestamp'),
    ('order_refunded', 'user_id'),
    ('order_refunded', 'uuid'),
    ('order_refunded', 'uuid_ts'),
    ('pages', 'anonymous_id'),
    ('pages', 'context_campaign_content'),
    ('pages', 'context_campaign_medium'),
    ('pages', 'context_campaign_name'),
    ('pages', 'context_campaign_source'),
    ('pages', 'context_google_analytics_client_id'),
    ('pages', 'context_integration_name'),
    ('pages', 'context_integration_version'),
    ('pages', 'context_ip'),
    ('pages', 'context_library_name'),
    ('pages', 'context_library_version'),
    ('pages', 'context_locale'),
    ('pages', 'context_page_path'),
    ('pages', 'context_page_referrer'),
    ('pages', 'context_page_search'),
    ('pages', 'context_page_title'),
    ('pages', 'context_page_url'),
    ('pages', 'context_traits_default_address_city'),
    ('pages', 'context_traits_default_address_country'),
    ('pages', 'context_traits_default_address_postal_code'),
    ('pages', 'context_traits_default_address_state'),
    ('pages', 'context_traits_default_address_street'),
    ('pages', 'context_traits_email'),
    ('pages', 'context_traits_phone'),
    ('pages', 'context_user_agent'),
    ('pages', 'email'),
    ('pages', 'id'),
    ('pages', 'name'),
    ('pages', 'original_timestamp'),
    ('pages', 'path'),
    ('pages', 'received_at'),
    ('pages', 'referrer'),
    ('pages', 'search'),
    ('pages', 'sent_at'),
    ('pages', 'timestamp'),
    ('pages', 'title'),
    ('pages', 'url'),
    ('pages', 'user_id'),
    ('pages', 'uuid'),
    ('pages', 'uuid_ts'),
    ('payment_failure', '_id'),
    ('payment_failure', 'accepts_marketing'),
    ('payment_failure', 'address_city'),
    ('payment_failure', 'address_country'),
    ('payment_failure', 'address_postal_code'),
    ('payment_failure', 'address_state'),
    ('payment_failure', 'address_street'),
    ('payment_failure', 'anonymous_id'),
    ('payment_failure', 'category'),
    ('payment_failure', 'context_google_analytics_client_id'),
    ('payment_failure', 'context_google_analytics_geoid'),
    ('payment_failure', 'context_integration_name'),
    ('payment_failure', 'context_integration_version'),
    ('payment_failure', 'context_library_name'),
    ('payment_failure', 'context_library_version'),
    ('payment_failure', 'email'),
    ('payment_failure', 'event'),
    ('payment_failure', 'event_text'),
    ('payment_failure', 'first_name'),
    ('payment_failure', 'id'),
    ('payment_failure', 'last_name'),
    ('payment_failure', 'original_timestamp'),
    ('payment_failure', 'presentment_currency'),
    ('payment_failure', 'received_at'),
    ('payment_failure', 'sent_at'),
    ('payment_failure', 'sent_from'),
    ('payment_failure', 'timestamp'),
    ('payment_failure', 'user_id'),
    ('payment_failure', 'uuid'),
    ('payment_failure', 'uuid_ts'),
    ('payment_info_entered', 'action_source'),
    ('payment_info_entered', 'anonymous_id'),
    ('payment_info_entered', 'cart_id'),
    ('payment_info_entered', 'category'),
    ('payment_info_entered', 'checkout_id'),
    ('payment_info_entered', 'context_external_ids'),
    ('payment_info_entered', 'context_google_analytics_client_id'),
    ('payment_info_entered', 'context_google_analytics_geoid'),
    ('payment_info_entered', 'context_integration_name'),
    ('payment_info_entered', 'context_integration_version'),
    ('payment_info_entered', 'context_ip'),
    ('payment_info_entered', 'context_library_name'),
    ('payment_info_entered', 'context_library_version'),
    ('payment_info_entered', 'coupon'),
    ('payment_info_entered', 'currency'),
    ('payment_info_entered', 'discount'),
    ('payment_info_entered', 'email'),
    ('payment_info_entered', 'event'),
    ('payment_info_entered', 'event_text'),
    ('payment_info_entered', 'fbp'),
    ('payment_info_entered', 'id'),
    ('payment_info_entered', 'original_timestamp'),
    ('payment_info_entered', 'payment_method'),
    ('payment_info_entered', 'presentment_currency'),
    ('payment_info_entered', 'products'),
    ('payment_info_entered', 'received_at'),
    ('payment_info_entered', 'sent_at'),
    ('payment_info_entered', 'sent_from'),
    ('payment_info_entered', 'shipping_method'),
    ('payment_info_entered', 'source_name'),
    ('payment_info_entered', 'step'),
    ('payment_info_entered', 'timestamp'),
    ('payment_info_entered', 'user_id'),
    ('payment_info_entered', 'uuid'),
    ('payment_info_entered', 'uuid_ts'),
    ('product_added', '_id'),
    ('product_added', 'action_source'),
    ('product_added', 'anonymous_id'),
    ('product_added', 'brand'),
    ('product_added', 'cart_id'),
    ('product_added', 'category'),
    ('product_added', 'compare_at_price'),
    ('product_added', 'context_google_analytics_client_id'),
    ('product_added', 'context_integration_name'),
    ('product_added', 'context_integration_version'),
    ('product_added', 'context_ip'),
    ('product_added', 'context_library_name'),
    ('product_added', 'context_library_version'),
    ('product_added', 'context_locale'),
    ('product_added', 'context_page_path'),
    ('product_added', 'context_page_referrer'),
    ('product_added', 'context_page_search'),
    ('product_added', 'context_page_title'),
    ('product_added', 'context_page_url'),
    ('product_added', 'context_user_agent'),
    ('product_added', 'currency'),
    ('product_added', 'email'),
    ('product_added', 'event'),
    ('product_added', 'event_text'),
    ('product_added', 'fbc'),
    ('product_added', 'fbp'),
    ('product_added', 'id'),
    ('product_added', 'image_url'),
    ('product_added', 'name'),
    ('product_added', 'original_timestamp'),
    ('product_added', 'presentment_amount'),
    ('product_added', 'presentment_currency'),
    ('product_added', 'price'),
    ('product_added', 'product_id'),
    ('product_added', 'products'),
    ('product_added', 'properties_action_source'),
    ('product_added', 'properties_brand'),
    ('product_added', 'properties_cart_id'),
    ('product_added', 'properties_category'),
    ('product_added', 'properties_compare_at_price'),
    ('product_added', 'properties_currency'),
    ('product_added', 'properties_email'),
    ('product_added', 'properties_image_url'),
    ('product_added', 'properties_name'),
    ('product_added', 'properties_presentment_amount'),
    ('product_added', 'properties_presentment_currency'),
    ('product_added', 'properties_price'),
    ('product_added', 'properties_product_id'),
    ('product_added', 'properties_products'),
    ('product_added', 'properties_quantity'),
    ('product_added', 'properties_sent_from'),
    ('product_added', 'properties_shopify_product_id'),
    ('product_added', 'properties_shopify_variant_id'),
    ('product_added', 'properties_url'),
    ('product_added', 'properties_variant'),
    ('product_added', 'quantity'),
    ('product_added', 'received_at'),
    ('product_added', 'sent_at'),
    ('product_added', 'sent_from'),
    ('product_added', 'shopify_product_id'),
    ('product_added', 'shopify_variant_id'),
    ('product_added', 'sku'),
    ('product_added', 'timestamp'),
    ('product_added', 'type'),
    ('product_added', 'url'),
    ('product_added', 'user_id'),
    ('product_added', 'uuid'),
    ('product_added', 'uuid_ts'),
    ('product_added', 'variant'),
    ('product_added2', '_id'),
    ('product_added2', 'anonymous_id'),
    ('product_added2', 'context_ip'),
    ('product_added2', 'context_library_name'),
    ('product_added2', 'context_library_version'),
    ('product_added2', 'context_locale'),
    ('product_added2', 'context_page_path'),
    ('product_added2', 'context_page_referrer'),
    ('product_added2', 'context_page_title'),
    ('product_added2', 'context_page_url'),
    ('product_added2', 'context_user_agent'),
    ('product_added2', 'event'),
    ('product_added2', 'event_text'),
    ('product_added2', 'id'),
    ('product_added2', 'original_timestamp'),
    ('product_added2', 'quantity'),
    ('product_added2', 'received_at'),
    ('product_added2', 'sent_at'),
    ('product_added2', 'timestamp'),
    ('product_added2', 'uuid'),
    ('product_added2', 'uuid_ts'),
    ('product_added3', 'anonymous_id'),
    ('product_added3', 'brand'),
    ('product_added3', 'context_ip'),
    ('product_added3', 'context_library_name'),
    ('product_added3', 'context_library_version'),
    ('product_added3', 'context_locale'),
    ('product_added3', 'context_page_path'),
    ('product_added3', 'context_page_referrer'),
    ('product_added3', 'context_page_title'),
    ('product_added3', 'context_page_url'),
    ('product_added3', 'context_user_agent'),
    ('product_added3', 'event'),
    ('product_added3', 'event_text'),
    ('product_added3', 'id'),
    ('product_added3', 'name'),
    ('product_added3', 'original_timestamp'),
    ('product_added3', 'price'),
    ('product_added3', 'product_id'),
    ('product_added3', 'quantity'),
    ('product_added3', 'received_at'),
    ('product_added3', 'sent_at'),
    ('product_added3', 'timestamp'),
    ('product_added3', 'url'),
    ('product_added3', 'uuid'),
    ('product_added3', 'uuid_ts'),
    ('product_added4', '_id'),
    ('product_added4', 'anonymous_id'),
    ('product_added4', 'context_ip'),
    ('product_added4', 'context_library_name'),
    ('product_added4', 'context_library_version'),
    ('product_added4', 'context_locale'),
    ('product_added4', 'context_page_path'),
    ('product_added4', 'context_page_referrer'),
    ('product_added4', 'context_page_title'),
    ('product_added4', 'context_page_url'),
    ('product_added4', 'context_user_agent'),
    ('product_added4', 'event'),
    ('product_added4', 'event_text'),
    ('product_added4', 'id'),
    ('product_added4', 'original_timestamp'),
    ('product_added4', 'quantity'),
    ('product_added4', 'received_at'),
    ('product_added4', 'sent_at'),
    ('product_added4', 'timestamp'),
    ('product_added4', 'uuid'),
    ('product_added4', 'uuid_ts'),
    ('product_clicked', 'anonymous_id'),
    ('product_clicked', 'brand'),
    ('product_clicked', 'category'),
    ('product_clicked', 'compare_at_price'),
    ('product_clicked', 'context_campaign_content'),
    ('product_clicked', 'context_campaign_medium'),
    ('product_clicked', 'context_campaign_name'),
    ('product_clicked', 'context_campaign_source'),
    ('product_clicked', 'context_google_analytics_client_id'),
    ('product_clicked', 'context_integration_name'),
    ('product_clicked', 'context_integration_version'),
    ('product_clicked', 'context_ip'),
    ('product_clicked', 'context_library_name'),
    ('product_clicked', 'context_library_version'),
    ('product_clicked', 'context_locale'),
    ('product_clicked', 'context_page_path'),
    ('product_clicked', 'context_page_referrer'),
    ('product_clicked', 'context_page_search'),
    ('product_clicked', 'context_page_title'),
    ('product_clicked', 'context_page_url'),
    ('product_clicked', 'context_traits_default_address_city'),
    ('product_clicked', 'context_traits_default_address_country'),
    ('product_clicked', 'context_traits_default_address_postal_code'),
    ('product_clicked', 'context_traits_default_address_state'),
    ('product_clicked', 'context_traits_default_address_street'),
    ('product_clicked', 'context_traits_email'),
    ('product_clicked', 'context_traits_phone'),
    ('product_clicked', 'context_user_agent'),
    ('product_clicked', 'currency'),
    ('product_clicked', 'email'),
    ('product_clicked', 'event'),
    ('product_clicked', 'event_text'),
    ('product_clicked', 'id'),
    ('product_clicked', 'image_url'),
    ('product_clicked', 'list_id'),
    ('product_clicked', 'name'),
    ('product_clicked', 'original_timestamp'),
    ('product_clicked', 'position'),
    ('product_clicked', 'price'),
    ('product_clicked', 'product_id'),
    ('product_clicked', 'received_at'),
    ('product_clicked', 'sent_at'),
    ('product_clicked', 'sent_from'),
    ('product_clicked', 'shopify_product_id'),
    ('product_clicked', 'shopify_variant_id'),
    ('product_clicked', 'sku'),
    ('product_clicked', 'tags'),
    ('product_clicked', 'timestamp'),
    ('product_clicked', 'url'),
    ('product_clicked', 'user_id'),
    ('product_clicked', 'uuid'),
    ('product_clicked', 'uuid_ts'),
    ('product_clicked', 'variant'),
    ('product_image_clicked', 'anonymous_id'),
    ('product_image_clicked', 'brand'),
    ('product_image_clicked', 'category'),
    ('product_image_clicked', 'compare_at_price'),
    ('product_image_clicked', 'context_google_analytics_client_id'),
    ('product_image_clicked', 'context_integration_name'),
    ('product_image_clicked', 'context_integration_version'),
    ('product_image_clicked', 'context_ip'),
    ('product_image_clicked', 'context_library_name'),
    ('product_image_clicked', 'context_library_version'),
    ('product_image_clicked', 'context_locale'),
    ('product_image_clicked', 'context_page_path'),
    ('product_image_clicked', 'context_page_referrer'),
    ('product_image_clicked', 'context_page_search'),
    ('product_image_clicked', 'context_page_title'),
    ('product_image_clicked', 'context_page_url'),
    ('product_image_clicked', 'context_traits_default_address_city'),
    ('product_image_clicked', 'context_traits_default_address_country'),
    ('product_image_clicked', 'context_traits_default_address_postal_code'),
    ('product_image_clicked', 'context_traits_default_address_state'),
    ('product_image_clicked', 'context_traits_default_address_street'),
    ('product_image_clicked', 'context_traits_email'),
    ('product_image_clicked', 'context_traits_phone'),
    ('product_image_clicked', 'context_user_agent'),
    ('product_image_clicked', 'currency'),
    ('product_image_clicked', 'email'),
    ('product_image_clicked', 'event'),
    ('product_image_clicked', 'event_text'),
    ('product_image_clicked', 'id'),
    ('product_image_clicked', 'image_url'),
    ('product_image_clicked', 'name'),
    ('product_image_clicked', 'original_timestamp'),
    ('product_image_clicked', 'position'),
    ('product_image_clicked', 'price'),
    ('product_image_clicked', 'product_id'),
    ('product_image_clicked', 'received_at'),
    ('product_image_clicked', 'sent_at'),
    ('product_image_clicked', 'sent_from'),
    ('product_image_clicked', 'shopify_product_id'),
    ('product_image_clicked', 'shopify_variant_id'),
    ('product_image_clicked', 'sku'),
    ('product_image_clicked', 'tags'),
    ('product_image_clicked', 'timestamp'),
    ('product_image_clicked', 'url'),
    ('product_image_clicked', 'user_id'),
    ('product_image_clicked', 'uuid'),
    ('product_image_clicked', 'uuid_ts'),
    ('product_image_clicked', 'variant'),
    ('product_list_viewed', 'anonymous_id'),
    ('product_list_viewed', 'category'),
    ('product_list_viewed', 'context_campaign_content'),
    ('product_list_viewed', 'context_campaign_medium'),
    ('product_list_viewed', 'context_campaign_name'),
    ('product_list_viewed', 'context_campaign_source'),
    ('product_list_viewed', 'context_google_analytics_client_id'),
    ('product_list_viewed', 'context_integration_name'),
    ('product_list_viewed', 'context_integration_version'),
    ('product_list_viewed', 'context_ip'),
    ('product_list_viewed', 'context_library_name'),
    ('product_list_viewed', 'context_library_version'),
    ('product_list_viewed', 'context_locale'),
    ('product_list_viewed', 'context_page_path'),
    ('product_list_viewed', 'context_page_referrer'),
    ('product_list_viewed', 'context_page_search'),
    ('product_list_viewed', 'context_page_title'),
    ('product_list_viewed', 'context_page_url'),
    ('product_list_viewed', 'context_traits_default_address_city'),
    ('product_list_viewed', 'context_traits_default_address_country'),
    ('product_list_viewed', 'context_traits_default_address_postal_code'),
    ('product_list_viewed', 'context_traits_default_address_state'),
    ('product_list_viewed', 'context_traits_default_address_street'),
    ('product_list_viewed', 'context_traits_email'),
    ('product_list_viewed', 'context_traits_phone'),
    ('product_list_viewed', 'context_user_agent'),
    ('product_list_viewed', 'email'),
    ('product_list_viewed', 'event'),
    ('product_list_viewed', 'event_text'),
    ('product_list_viewed', 'id'),
    ('product_list_viewed', 'list_id'),
    ('product_list_viewed', 'original_timestamp'),
    ('product_list_viewed', 'products'),
    ('product_list_viewed', 'received_at'),
    ('product_list_viewed', 'sent_at'),
    ('product_list_viewed', 'sent_from'),
    ('product_list_viewed', 'timestamp'),
    ('product_list_viewed', 'user_id'),
    ('product_list_viewed', 'uuid'),
    ('product_list_viewed', 'uuid_ts'),
    ('product_removed', 'action_source'),
    ('product_removed', 'anonymous_id'),
    ('product_removed', 'brand'),
    ('product_removed', 'cart_id'),
    ('product_removed', 'category'),
    ('product_removed', 'compare_at_price'),
    ('product_removed', 'context_google_analytics_client_id'),
    ('product_removed', 'context_integration_name'),
    ('product_removed', 'context_integration_version'),
    ('product_removed', 'context_ip'),
    ('product_removed', 'context_library_name'),
    ('product_removed', 'context_library_version'),
    ('product_removed', 'context_locale'),
    ('product_removed', 'context_page_path'),
    ('product_removed', 'context_page_referrer'),
    ('product_removed', 'context_page_search'),
    ('product_removed', 'context_page_title'),
    ('product_removed', 'context_page_url'),
    ('product_removed', 'context_user_agent'),
    ('product_removed', 'currency'),
    ('product_removed', 'email'),
    ('product_removed', 'event'),
    ('product_removed', 'event_text'),
    ('product_removed', 'fbc'),
    ('product_removed', 'fbp'),
    ('product_removed', 'id'),
    ('product_removed', 'image_url'),
    ('product_removed', 'name'),
    ('product_removed', 'original_timestamp'),
    ('product_removed', 'presentment_amount'),
    ('product_removed', 'presentment_currency'),
    ('product_removed', 'price'),
    ('product_removed', 'product_id'),
    ('product_removed', 'products'),
    ('product_removed', 'quantity'),
    ('product_removed', 'received_at'),
    ('product_removed', 'sent_at'),
    ('product_removed', 'sent_from'),
    ('product_removed', 'shopify_product_id'),
    ('product_removed', 'shopify_variant_id'),
    ('product_removed', 'sku'),
    ('product_removed', 'timestamp'),
    ('product_removed', 'url'),
    ('product_removed', 'user_id'),
    ('product_removed', 'uuid'),
    ('product_removed', 'uuid_ts'),
    ('product_removed', 'variant'),
    ('product_viewed', 'anonymous_id'),
    ('product_viewed', 'brand'),
    ('product_viewed', 'category'),
    ('product_viewed', 'compare_at_price'),
    ('product_viewed', 'context_google_analytics_client_id'),
    ('product_viewed', 'context_integration_name'),
    ('product_viewed', 'context_integration_version'),
    ('product_viewed', 'context_ip'),
    ('product_viewed', 'context_library_name'),
    ('product_viewed', 'context_library_version'),
    ('product_viewed', 'context_locale'),
    ('product_viewed', 'context_page_path'),
    ('product_viewed', 'context_page_referrer'),
    ('product_viewed', 'context_page_search'),
    ('product_viewed', 'context_page_title'),
    ('product_viewed', 'context_page_url'),
    ('product_viewed', 'context_traits_default_address_city'),
    ('product_viewed', 'context_traits_default_address_country'),
    ('product_viewed', 'context_traits_default_address_postal_code'),
    ('product_viewed', 'context_traits_default_address_state'),
    ('product_viewed', 'context_traits_default_address_street'),
    ('product_viewed', 'context_traits_email'),
    ('product_viewed', 'context_traits_phone'),
    ('product_viewed', 'context_user_agent'),
    ('product_viewed', 'currency'),
    ('product_viewed', 'email'),
    ('product_viewed', 'event'),
    ('product_viewed', 'event_text'),
    ('product_viewed', 'id'),
    ('product_viewed', 'image_url'),
    ('product_viewed', 'name'),
    ('product_viewed', 'original_timestamp'),
    ('product_viewed', 'position'),
    ('product_viewed', 'price'),
    ('product_viewed', 'product_id'),
    ('product_viewed', 'received_at'),
    ('product_viewed', 'sent_at'),
    ('product_viewed', 'sent_from'),
    ('product_viewed', 'shopify_product_id'),
    ('product_viewed', 'shopify_variant_id'),
    ('product_viewed', 'sku'),
    ('product_viewed', 'tags'),
    ('product_viewed', 'timestamp'),
    ('product_viewed', 'url'),
    ('product_viewed', 'user_id'),
    ('product_viewed', 'uuid'),
    ('product_viewed', 'uuid_ts'),
    ('product_viewed', 'variant'),
    ('products_searched', 'anonymous_id'),
    ('products_searched', 'category'),
    ('products_searched', 'context_google_analytics_client_id'),
    ('products_searched', 'context_integration_name'),
    ('products_searched', 'context_integration_version'),
    ('products_searched', 'context_ip'),
    ('products_searched', 'context_library_name'),
    ('products_searched', 'context_library_version'),
    ('products_searched', 'context_locale'),
    ('products_searched', 'context_page_path'),
    ('products_searched', 'context_page_referrer'),
    ('products_searched', 'context_page_search'),
    ('products_searched', 'context_page_title'),
    ('products_searched', 'context_page_url'),
    ('products_searched', 'context_traits_default_address_city'),
    ('products_searched', 'context_traits_default_address_country'),
    ('products_searched', 'context_traits_default_address_postal_code'),
    ('products_searched', 'context_traits_default_address_state'),
    ('products_searched', 'context_traits_default_address_street'),
    ('products_searched', 'context_traits_email'),
    ('products_searched', 'context_traits_phone'),
    ('products_searched', 'context_user_agent'),
    ('products_searched', 'email'),
    ('products_searched', 'event'),
    ('products_searched', 'event_text'),
    ('products_searched', 'id'),
    ('products_searched', 'original_timestamp'),
    ('products_searched', 'query'),
    ('products_searched', 'received_at'),
    ('products_searched', 'results'),
    ('products_searched', 'sent_at'),
    ('products_searched', 'sent_from'),
    ('products_searched', 'timestamp'),
    ('products_searched', 'user_id'),
    ('products_searched', 'uuid'),
    ('products_searched', 'uuid_ts'),
    ('referral_form_submitted', 'anonymous_id'),
    ('referral_form_submitted', 'context_google_analytics_client_id'),
    ('referral_form_submitted', 'context_ip'),
    ('referral_form_submitted', 'context_library_name'),
    ('referral_form_submitted', 'context_library_version'),
    ('referral_form_submitted', 'context_locale'),
    ('referral_form_submitted', 'context_page_path'),
    ('referral_form_submitted', 'context_page_title'),
    ('referral_form_submitted', 'context_page_url'),
    ('referral_form_submitted', 'context_user_agent'),
    ('referral_form_submitted', 'email'),
    ('referral_form_submitted', 'event'),
    ('referral_form_submitted', 'event_text'),
    ('referral_form_submitted', 'id'),
    ('referral_form_submitted', 'original_timestamp'),
    ('referral_form_submitted', 'received_at'),
    ('referral_form_submitted', 'referree_email'),
    ('referral_form_submitted', 'sent_at'),
    ('referral_form_submitted', 'timestamp'),
    ('referral_form_submitted', 'user_id'),
    ('referral_form_submitted', 'uuid'),
    ('referral_form_submitted', 'uuid_ts'),
    ('referral_non_logged_in', 'anonymous_id'),
    ('referral_non_logged_in', 'context_google_analytics_client_id'),
    ('referral_non_logged_in', 'context_ip'),
    ('referral_non_logged_in', 'context_library_name'),
    ('referral_non_logged_in', 'context_library_version'),
    ('referral_non_logged_in', 'context_locale'),
    ('referral_non_logged_in', 'context_page_path'),
    ('referral_non_logged_in', 'context_page_title'),
    ('referral_non_logged_in', 'context_page_url'),
    ('referral_non_logged_in', 'context_user_agent'),
    ('referral_non_logged_in', 'email'),
    ('referral_non_logged_in', 'event'),
    ('referral_non_logged_in', 'event_text'),
    ('referral_non_logged_in', 'id'),
    ('referral_non_logged_in', 'original_timestamp'),
    ('referral_non_logged_in', 'received_at'),
    ('referral_non_logged_in', 'sent_at'),
    ('referral_non_logged_in', 'timestamp'),
    ('referral_non_logged_in', 'user_id'),
    ('referral_non_logged_in', 'uuid'),
    ('referral_non_logged_in', 'uuid_ts'),
    ('registration_viewed', 'anonymous_id'),
    ('registration_viewed', 'category'),
    ('registration_viewed', 'context_google_analytics_client_id'),
    ('registration_viewed', 'context_integration_name'),
    ('registration_viewed', 'context_integration_version'),
    ('registration_viewed', 'context_ip'),
    ('registration_viewed', 'context_library_name'),
    ('registration_viewed', 'context_library_version'),
    ('registration_viewed', 'context_locale'),
    ('registration_viewed', 'context_page_path'),
    ('registration_viewed', 'context_page_referrer'),
    ('registration_viewed', 'context_page_title'),
    ('registration_viewed', 'context_page_url'),
    ('registration_viewed', 'context_user_agent'),
    ('registration_viewed', 'event'),
    ('registration_viewed', 'event_text'),
    ('registration_viewed', 'id'),
    ('registration_viewed', 'original_timestamp'),
    ('registration_viewed', 'received_at'),
    ('registration_viewed', 'sent_at'),
    ('registration_viewed', 'sent_from'),
    ('registration_viewed', 'timestamp'),
    ('registration_viewed', 'user_id'),
    ('registration_viewed', 'uuid'),
    ('registration_viewed', 'uuid_ts'),
    ('test', 'anonymous_id'),
    ('test', 'context_google_analytics_client_id'),
    ('test', 'context_ip'),
    ('test', 'context_library_name'),
    ('test', 'context_library_version'),
    ('test', 'context_locale'),
    ('test', 'context_page_path'),
    ('test', 'context_page_title'),
    ('test', 'context_page_url'),
    ('test', 'context_user_agent'),
    ('test', 'event'),
    ('test', 'event_text'),
    ('test', 'id'),
    ('test', 'original_timestamp'),
    ('test', 'received_at'),
    ('test', 'sent_at'),
    ('test', 'timestamp'),
    ('test', 'uuid'),
    ('test', 'uuid_ts'),
    ('thankyou_page_viewed', 'anonymous_id'),
    ('thankyou_page_viewed', 'category'),
    ('thankyou_page_viewed', 'context_google_analytics_client_id'),
    ('thankyou_page_viewed', 'context_integration_name'),
    ('thankyou_page_viewed', 'context_ip'),
    ('thankyou_page_viewed', 'context_library_name'),
    ('thankyou_page_viewed', 'context_library_version'),
    ('thankyou_page_viewed', 'context_locale'),
    ('thankyou_page_viewed', 'context_page_path'),
    ('thankyou_page_viewed', 'context_page_referrer'),
    ('thankyou_page_viewed', 'context_page_title'),
    ('thankyou_page_viewed', 'context_page_url'),
    ('thankyou_page_viewed', 'context_user_agent'),
    ('thankyou_page_viewed', 'currency'),
    ('thankyou_page_viewed', 'discount'),
    ('thankyou_page_viewed', 'email'),
    ('thankyou_page_viewed', 'event'),
    ('thankyou_page_viewed', 'event_text'),
    ('thankyou_page_viewed', 'id'),
    ('thankyou_page_viewed', 'order_id'),
    ('thankyou_page_viewed', 'original_timestamp'),
    ('thankyou_page_viewed', 'presentment_currency'),
    ('thankyou_page_viewed', 'presentment_total'),
    ('thankyou_page_viewed', 'products'),
    ('thankyou_page_viewed', 'received_at'),
    ('thankyou_page_viewed', 'sent_at'),
    ('thankyou_page_viewed', 'sent_from'),
    ('thankyou_page_viewed', 'shipping'),
    ('thankyou_page_viewed', 'tax'),
    ('thankyou_page_viewed', 'timestamp'),
    ('thankyou_page_viewed', 'total'),
    ('thankyou_page_viewed', 'user_id'),
    ('thankyou_page_viewed', 'uuid'),
    ('thankyou_page_viewed', 'uuid_ts'),
    ('tracks', 'anonymous_id'),
    ('tracks', 'context_campaign_content'),
    ('tracks', 'context_campaign_medium'),
    ('tracks', 'context_campaign_name'),
    ('tracks', 'context_campaign_source'),
    ('tracks', 'context_external_ids'),
    ('tracks', 'context_google_analytics_client_id'),
    ('tracks', 'context_google_analytics_geoid'),
    ('tracks', 'context_integration_name'),
    ('tracks', 'context_integration_version'),
    ('tracks', 'context_ip'),
    ('tracks', 'context_library_name'),
    ('tracks', 'context_library_version'),
    ('tracks', 'context_locale'),
    ('tracks', 'context_page_path'),
    ('tracks', 'context_page_referrer'),
    ('tracks', 'context_page_search'),
    ('tracks', 'context_page_title'),
    ('tracks', 'context_page_url'),
    ('tracks', 'context_traits_default_address_city'),
    ('tracks', 'context_traits_default_address_country'),
    ('tracks', 'context_traits_default_address_postal_code'),
    ('tracks', 'context_traits_default_address_state'),
    ('tracks', 'context_traits_default_address_street'),
    ('tracks', 'context_traits_email'),
    ('tracks', 'context_traits_phone'),
    ('tracks', 'context_user_agent'),
    ('tracks', 'event'),
    ('tracks', 'event_text'),
    ('tracks', 'id'),
    ('tracks', 'original_timestamp'),
    ('tracks', 'received_at'),
    ('tracks', 'sent_at'),
    ('tracks', 'timestamp'),
    ('tracks', 'user_id'),
    ('tracks', 'uuid'),
    ('tracks', 'uuid_ts'),
    ('users', '_id'),
    ('users', 'accepts_marketing'),
    ('users', 'context_campaign_content'),
    ('users', 'context_campaign_medium'),
    ('users', 'context_campaign_source'),
    ('users', 'context_google_analytics_client_id'),
    ('users', 'context_ip'),
    ('users', 'context_library_name'),
    ('users', 'context_library_version'),
    ('users', 'context_locale'),
    ('users', 'context_page_path'),
    ('users', 'context_page_referrer'),
    ('users', 'context_page_search'),
    ('users', 'context_page_title'),
    ('users', 'context_page_url'),
    ('users', 'context_user_agent'),
    ('users', 'created_at'),
    ('users', 'customer_lifetime_value'),
    ('users', 'default_address_city'),
    ('users', 'default_address_country'),
    ('users', 'default_address_postal_code'),
    ('users', 'default_address_state'),
    ('users', 'default_address_street'),
    ('users', 'email'),
    ('users', 'first_name'),
    ('users', 'id'),
    ('users', 'last_name'),
    ('users', 'marketing_opt_in'),
    ('users', 'phone'),
    ('users', 'presentment_currency'),
    ('users', 'purchase_count'),
    ('users', 'received_at'),
    ('users', 'state'),
    ('users', 'tags'),
    ('users', 'uuid'),
    ('users', 'uuid_ts'),
    ('users', 'verified_email')
]

def make_base_cte(table_names, column_names, table_column_pairs):
    q = """
    WITH base AS (
    """

    loop_ct = 0
    for t in table_names:
        if loop_ct > 0:
            q += """

            UNION ALL

            """

        col_list = [f"'{t}' as src_tbl"]
        for c in column_names:
            if (t, c) in table_column_pairs:
                col_list.append(
                    f"""
                    {t}.{c}"""
                )
            else:
                col_list.append(
                    f"""
                    NULL AS {c}"""
                )

        q += f"""
        SELECT
        {','.join(col_list)}
        FROM {SCHEMA_NAME}.{t}
        """

        loop_ct += 1

    q += ")"

    return q


def make_id_map_cte():
    q = """
    id_map AS (
        select
            anonymous_id
            , user_id
        from (
            select
                anonymous_id
                , user_id
                , row_number() over (
                    partition by anonymous_id
                    order by timestamp
                ) as rn
            from shopify_littledata_prod.identifies
            where user_id is not null
        )
        where rn = 1
    )
    """

    return q

def session_maker_cte():
    q = """
        , session_maker as (
            select *
                , case
                    when datediff('s',
                            lag(event_ts) over(
                                partition by anonymous_id
                                order by event_ts
                            ),
                            event_ts
                        ) > 60 * 30
                        OR lag(event_ts) over(
                                partition by anonymous_id
                                order by event_ts
                            ) IS NULL
                    then event_id end as session_id_tmp
            from all_events
        )
        , sessioned_events as (
            select *
                , last_value(session_id_tmp IGNORE NULLS) over (order by anonymous_id, event_ts rows unbounded preceding) as session_id
            from session_maker
        )
    """

if __name__ == '__main__':
    base_cte = make_base_cte(segment_table_names, segment_column_names, segment_table_column_pairs)
    identity_mapping_cte = make_id_map_cte()
    print(base_cte)
