select
event as src_tbl,
anonymous_id,
context_campaign_content,
context_campaign_medium,
context_campaign_name,
context_campaign_source,
context_ip,
context_library_name,
context_library_version,
context_locale,
context_page_path,
context_page_referrer,
context_page_search,
context_page_title,
context_page_url,
context_user_agent,
event,
event_text,
id,
master_user_id,
original_timestamp,
received_at,
sent_at,
session_id,
session_id_tmp,
"timestamp",
user_id,
uuid,
uuid_ts,
null as email,
product_id,
true as replatform
From {{ref('sessioned_events')}}

Union all

select 
src_tbl,
anonymous_id,
context_campaign_content,
context_campaign_medium,
context_campaign_name,
context_campaign_source,
context_ip,
context_library_name,
context_library_version,
context_locale,
context_page_path,
context_page_referrer,
context_page_search,
context_page_title,
context_page_url,
context_user_agent,
event,
event_text,
id,
master_user_id,
original_timestamp,
received_at,
sent_at,
session_id,
session_id_tmp,
"timestamp",
user_id,
uuid,
uuid_ts,
email,
product_id,
false as replatform
From {{ref('sessioned_events_shopify')}}
