/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'introduction',
    {type: 'category', label: 'Getting Started', items: [
      {type: 'category', label: 'Data Engineering', items: [
      'foundations/basics/de-basics',
      'foundations/basics/data-pipelines',
      'foundations/basics/oltp-vs-olap',
      'foundations/basics/data-storages',
      'foundations/basics/sql-vs-nosql',
      'foundations/basics/big-data',
      'foundations/basics/batch-vs-incremental',
      'foundations/basics/data-contract',
      'foundations/basics/data-governance',
      'foundations/basics/data-management',
      'foundations/basics/data-quality',
      'foundations/basics/batch-data-processing',
      'foundations/basics/stream-data-processing',
      'foundations/basics/most-common-interview-questions-set1',
      'foundations/basics/most-common-interview-questions-set2',
      'foundations/basics/most-common-interview-questions-set3',
      ]},
      {type: 'category', label: 'Spark and Hadoop', items: [
        'foundations/basics/spark-basics',
        'foundations/basics/spark-origin',
        'foundations/basics/hadoop-basics',
        'foundations/basics/map-reduce',
        'foundations/basics/hadoop-vs-spark',
        'foundations/basics/spark-dag',
        'foundations/basics/rdd',
        'foundations/basics/spark-quiz',
        ]},
        {type: 'category', label: 'Developer Essentials', items: [
          'foundations/developer/install-anaconda',
          'foundations/developer/install-jupyter',
          'foundations/developer/install-vscode',
          'foundations/developer/lab-explore-vscode-features',
          'foundations/developer/setup-git',
          'foundations/developer/lab-learn-git-commands',
          'foundations/developer/lab-bash-commands/index',
          'foundations/developer/install-dbeaver',
          ]},
    ]},
    {type: 'category', label: 'Cloud Computing', items: [
      {type: 'category', label: 'Introduction', items: [
      'foundations/cloud/cloud-basics',
      'foundations/cloud/cloud-comparison',
      ]},
      {type: 'category', label: 'AWS', items: [
        'foundations/cloud/ec2',
        'foundations/cloud/iam',
        'foundations/cloud/glue',
        'foundations/cloud/rds',
        'foundations/cloud/s3',
        'foundations/cloud/dms',
        'foundations/cloud/secrets-manager',
        'foundations/cloud/aws-containers',
        'foundations/cloud/aws-commands',
        'foundations/cloud/lab-aws-setup/README',
        'foundations/cloud/lab-create-iam-policy-role/README',
        'foundations/cloud/lab-aws-secrets-manager/README',
        'foundations/cloud/lab-create-your-first-vpc/README',
        'foundations/cloud/lab-create-your-first-ec2-instance-linux/README',
        ]},
        {type: 'category', label: 'GCP', items: [
          'foundations/cloud/gcp-basics',
          'foundations/cloud/gcp-setup',
          ]},
        {type: 'category', label: 'Azure', items: [
          'foundations/cloud/azure-basics',
          'foundations/cloud/azure-data-ingestion',
          'foundations/cloud/azure-batch-processing',
          'foundations/cloud/azure-fullstack-solutions',
          ]},
    ]},
    {type: 'category', label: 'Programming', items: [
      {type: 'category', label: 'SQL', items: [
      'foundations/language/sql/sql-basics',
      'foundations/language/sql/sql-query',
      'foundations/language/sql/commands/index',
      'foundations/language/sql/cte',
      'foundations/language/sql/subquery',
      'foundations/language/sql/views',
      'foundations/language/sql/stored-procedures',
      'foundations/language/sql/triggers',
      'foundations/language/sql/indexes',
      'foundations/language/sql/comparison-operators',
      'foundations/language/sql/logical-operators',
      'foundations/language/sql/joins',
      'foundations/language/sql/comments',
      'foundations/language/sql/cursor',
      'foundations/language/sql/aggregate-functions',
      'foundations/language/sql/string-functions',
      'foundations/language/sql/date-functions',
      'foundations/language/sql/window-functions',
      'foundations/language/sql/performance-tuning',
      'foundations/language/sql/joins',
      'foundations/language/sql/lab-mysql-data-ingestion/index',
      'foundations/language/sql/lab-basic-to-advanced/index',
      'foundations/language/sql/lab-postgres-queries/index',
      'foundations/language/sql/lab-postgres-sales/index',
      'foundations/language/sql/lab-sqlite-basics/index',
      'foundations/language/sql/challenges/yammer/index',
      'foundations/language/sql/challenges/braintree/index',
      'foundations/language/sql/challenges/employee',
      'foundations/language/sql/challenges/assignment5/index',
      'foundations/language/sql/links'
      ]},
      {type: 'category', label: 'Python', items: [
      'foundations/language/python/introduction-to-python',
      'foundations/language/python/python-syntax-sugars',
      'foundations/language/python/lab-etl-csv-json-xml/index',
      'datascience/nlp/lab-basic-text-handlng-python/index',
      'foundations/language/python/links',
      ]},
      {type: 'category', label: 'PySpark', items: [
      'foundations/language/pyspark/install',
      'foundations/language/pyspark/dataframe',
      'foundations/language/pyspark/methods-operations',
      'foundations/language/pyspark/partitioning',
      'foundations/language/pyspark/lazy-processing',
      'foundations/language/pyspark/caching',
      'foundations/language/pyspark/udf',
      'foundations/language/pyspark/broadcasting',
      'foundations/language/pyspark/cheat-sheet',
      'foundations/language/pyspark/execution-plan',
      'foundations/language/pyspark/pyspark-vs-pandas',
      'foundations/language/pyspark/lab-pyspark-basics/index',
      'processing/databricks/lab-databricks-pyspark-s3/index',
      'foundations/language/pyspark/lab-spark-optimizations-2/README',
      'foundations/language/pyspark/lab-spark-optimizations/README',
      'foundations/language/pyspark/lab-uber-analysis/README',
      'foundations/language/pyspark/lab-understand-spark-query-execution/README',
      'foundations/language/pyspark/lab-bcg/README',
      'processing/databricks/lab-databricks-scala-postgres-s3/README',
      'foundations/language/pyspark/lab-calculating-partitions/README',
      ]},
      {type: 'category', label: 'Spark Scala', items: [
        'foundations/language/scala/lab-scala-getting-started/README',
      ]},
    ]},
    {type: 'category', label: 'Data Storage', items: [
      {type: 'category', label: 'Flat Files', items: [
        'storage/serialization',
        'storage/csv',
        'storage/xml',
        'storage/json',
        'storage/avro',
        'storage/parquet',
        'storage/orc',
        'storage/arrow',
        'storage/hudi',
        'storage/iceberg',
        'storage/database-storage-engines',
        'storage/avro-vs-parquet-vs-orc',
        'storage/parquet-vs-csv',
        'storage/lab-data-loading-python/README',
        'storage/lab-processing-json-data/README',
      ]},
      {type: 'category', label: 'Databases', items: [
        'storage/postgres',
        'storage/mysql',
        'storage/sqlite',
        'storage/duckdb',
        'storage/gcp-cloudsql',
        'storage/azure-sql',
        'storage/interview-questions',
        'storage/postgres-vs-mysql',
        'storage/lab-aws-rds-service/README',
        'storage/lab-mysql-data-ingestion/README',
        'storage/lab-sqlite-basics/README',
        'storage/lab-postgres-getting-started/README',
        'storage/lab-postgres-bash-etl/README',
        'storage/lab-postgres-crime-reports/README',
        'storage/lab-postgres-trips-stored-procedure/README',
        'storage/lab-mysql-police-api-etl/README',
        'storage/lab-gcp-cloudsql-nyctaxi/README',
        'storage/lab-azure-sql-securing-databases/README',
        'storage/lab-db2-bookshop-petsale-data-ingestion/README',
        'storage/lab-duckdb-analytics-bank-tpch-nyctaxi/README',
        'storage/lab-sqlite-hipolabs-api/README',
        'storage/database-links',
      ]},
      {type: 'category', label: 'NoSQL Databases', items: [
        'storage/cassandra',
        'storage/gcp-bigtable',
        'storage/aws-dynamodb',
        'storage/apache-couchdb',
        'storage/mongodb',
        'storage/lab-getting-started-with-cassandra/README',
        'storage/lab-gcp-streaming-bigtable/README',
        'storage/lab-amazon-keyspaces/README',
        'storage/lab-intro-to-dynamodb/README',
        'storage/lab-mongodb-basics/README',
        'storage/lab-couchdb-movies-data-migration/README'
      ]},
      {type: 'category', label: 'Warehouses', items: [
        'storage/data-warehouses',
        'storage/athena',
        'storage/project-athena-federated/README',
        'storage/redshift',
        'storage/lab-redshift-data-loading',
        'storage/lab-redshift-data-loading-analysis',
        'storage/lab-redshift-table-design-query-tuning',
        'storage/lab-redshift-scd',
        'storage/lab-redshift-scd-2',
        'storage/lab-redshift-ongoing-load-elt',
        'storage/lab-redshift-spectrum-query-datalake',
        'storage/lab-redshift-spectrum-query-tuning',
        'storage/bigquery',
        'storage/snowflake',
        'storage/warehouse-links',
      ]},
      {type: 'category', label: 'Data Lakes', items: [
        'storage/datalakes',
        'storage/why-datalakes',
        'storage/azure-datalake',
        'storage/gcs',
        'storage/lab-datalake-healthcare-s3-glue-athena/README',
        'storage/lab-adl-create-manage-data/README',
        'storage/lab-adl-securing-monitoring-lakes/README',
      ]},
      {type: 'category', label: 'Lakehouses', items: [
        'storage/data-lakehouses',
        'storage/deltalake',
        'storage/apache-hudi',
        'storage/apache-iceberg',
        'storage/lab-read-s3-delta-in-python/README',
        'storage/lab-glue-emr-iceberg-serverless-lakehouse/README',
        'storage/lab-production-cleaning-deltalake/README',
        'storage/lab-scd-glue-delta/README',
      ]},
      {type: 'category', label: 'Data Meshes', items: [
        'storage/data-mesh-basics',
        'storage/casestudy-messflix-hypothetical',
      ]},
    ]},
    {type: 'category', label: 'Data Processing', items: [
      {type: 'category', label: 'Databricks', items: [
        'processing/databricks/README',
        'processing/databricks/lab-cybersecurity-databricks/README',
        'processing/databricks/lab-databricks-clickstream/README',
        'processing/databricks/lab-databricks-deltalake/README',
        'processing/databricks/lab-deltalake-optimizations/README',
        'processing/databricks/lab-dlt-dbt/README',
        'processing/databricks/lab-healthcare-databricks/README',
        'processing/databricks/lab-iot-health-tracker/README',
        'processing/databricks/lab-loan-application/README',
        'processing/databricks/lab-retail-pos-databricks/README',
        'processing/databricks/lab-data-processing-azure-dbr/README',
        'processing/databricks/project-databricks-de/README',
        'processing/databricks/project-learnerbricks/README',
        'processing/databricks/project-advancedbricks/README',
        'processing/databricks/project-bedbricks/README',
        'processing/databricks/project-databricks-superset/README',
      ]},
    ]},
  ],
};

module.exports = sidebars;
