/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'introduction',
    {type: 'category', label: 'Getting Started', link: {type: 'generated-index'}, items: [
      {type: 'category', label: 'Data Engineering', link: {type: 'generated-index'}, items: [
      'foundations/basics/de-basics',
      'foundations/basics/data-pipelines',
      'foundations/basics/oltp-vs-olap',
      'foundations/basics/data-storages',
      'foundations/basics/sql-vs-nosql',
      'foundations/basics/big-data',
      'foundations/basics/batch-vs-incremental',
      'foundations/basics/data-contract',
      'foundations/basics/data-governance',
      'foundations/basics/data-management',
      'foundations/basics/data-quality',
      'foundations/basics/batch-data-processing',
      'foundations/basics/stream-data-processing',
      'orchestration/README',
      'foundations/basics/most-common-interview-questions-set1',
      'foundations/basics/most-common-interview-questions-set2',
      'foundations/basics/most-common-interview-questions-set3',
      ]},
      {type: 'category', label: 'Spark and Hadoop', link: {type: 'generated-index'}, items: [
        'foundations/basics/spark-basics',
        'foundations/basics/spark-origin',
        'foundations/basics/hadoop-basics',
        'foundations/basics/map-reduce',
        'foundations/basics/hadoop-vs-spark',
        'foundations/basics/spark-dag',
        'foundations/basics/rdd',
        'foundations/basics/spark-quiz',
        ]},
      {type: 'category', label: 'Developer Essentials', link: {type: 'generated-index'}, items: [
        'foundations/developer/install-anaconda',
        'foundations/developer/install-jupyter',
        'foundations/developer/install-vscode',
        'foundations/developer/lab-explore-vscode-features',
        'foundations/developer/setup-git',
        'foundations/developer/lab-learn-git-commands',
        'foundations/developer/lab-bash-commands/index',
        'foundations/developer/install-dbeaver',
        ]},
      {type: 'category', label: 'System Design', link: {type: 'doc', id: 'system-design/README'}, items: [
        'system-design/examples',
        'system-design/databricks-case-studies',
        ]},
    ]},
    {type: 'category', label: 'Cloud Computing', link: {type: 'doc', id: 'foundations/cloud/cloud-computing'}, items: [
      {type: 'category', label: 'AWS', link: {type: 'generated-index'}, items: [
        'foundations/cloud/ec2',
        'foundations/cloud/iam',
        'foundations/cloud/glue',
        'foundations/cloud/rds',
        'foundations/cloud/s3',
        'foundations/cloud/dms',
        'foundations/cloud/secrets-manager',
        'foundations/cloud/aws-containers',
        'foundations/cloud/aws-commands',
        'foundations/cloud/lab-aws-setup/README',
        'foundations/cloud/lab-create-iam-policy-role/README',
        'foundations/cloud/lab-aws-secrets-manager/README',
        'foundations/cloud/lab-create-your-first-vpc/README',
        'foundations/cloud/lab-create-your-first-ec2-instance-linux/README',
        ]},
        {type: 'category', label: 'GCP', link: {type: 'generated-index'}, items: [
          'foundations/cloud/gcp-basics',
          'foundations/cloud/gcp-setup',
          ]},
        {type: 'category', label: 'Azure', link: {type: 'generated-index'}, items: [
          'foundations/cloud/azure-basics',
          'foundations/cloud/azure-data-ingestion',
          'foundations/cloud/azure-batch-processing',
          'foundations/cloud/azure-fullstack-solutions',
          ]},
    ]},
    {type: 'category', label: 'Programming', items: [
      {type: 'category', label: 'SQL', link: {type: 'doc', id: 'foundations/language/sql/sql-basics'}, items: [
      'foundations/language/sql/sql-query',
      'foundations/language/sql/commands/index',
      'foundations/language/sql/cte',
      'foundations/language/sql/subquery',
      'foundations/language/sql/views',
      'foundations/language/sql/stored-procedures',
      'foundations/language/sql/triggers',
      'foundations/language/sql/indexes',
      'foundations/language/sql/comparison-operators',
      'foundations/language/sql/logical-operators',
      'foundations/language/sql/joins',
      'foundations/language/sql/comments',
      'foundations/language/sql/cursor',
      'foundations/language/sql/aggregate-functions',
      'foundations/language/sql/string-functions',
      'foundations/language/sql/date-functions',
      'foundations/language/sql/window-functions',
      'foundations/language/sql/performance-tuning',
      'foundations/language/sql/joins',
      'foundations/language/sql/lab-mysql-data-ingestion/index',
      'foundations/language/sql/lab-basic-to-advanced/index',
      'foundations/language/sql/lab-postgres-queries/index',
      'foundations/language/sql/lab-postgres-sales/index',
      'foundations/language/sql/lab-sqlite-basics/index',
      'foundations/language/sql/challenges/yammer/index',
      'foundations/language/sql/challenges/braintree/index',
      'foundations/language/sql/challenges/employee',
      'foundations/language/sql/challenges/assignment5/index',
      'foundations/language/sql/links'
      ]},
      {type: 'category', label: 'Python', items: [
      'foundations/language/python/introduction-to-python',
      'foundations/language/python/python-syntax-sugars',
      'foundations/language/python/lab-etl-csv-json-xml/index',
      'datascience/nlp/lab-basic-text-handlng-python/index',
      'foundations/language/python/links',
      ]},
      {type: 'category', label: 'PySpark', items: [
      'foundations/language/pyspark/install',
      'foundations/language/pyspark/dataframe',
      'foundations/language/pyspark/methods-operations',
      'foundations/language/pyspark/partitioning',
      'foundations/language/pyspark/lazy-processing',
      'foundations/language/pyspark/caching',
      'foundations/language/pyspark/udf',
      'foundations/language/pyspark/broadcasting',
      'foundations/language/pyspark/cheat-sheet',
      'foundations/language/pyspark/execution-plan',
      'foundations/language/pyspark/pyspark-vs-pandas',
      'foundations/language/pyspark/lab-pyspark-basics/index',
      'processing/databricks/lab-databricks-pyspark-s3/index',
      'foundations/language/pyspark/lab-spark-optimizations-2/README',
      'foundations/language/pyspark/lab-spark-optimizations/README',
      'foundations/language/pyspark/lab-uber-analysis/README',
      'foundations/language/pyspark/lab-understand-spark-query-execution/README',
      'foundations/language/pyspark/lab-bcg/README',
      'processing/databricks/lab-databricks-scala-postgres-s3/README',
      'foundations/language/pyspark/lab-calculating-partitions/README',
      ]},
      {type: 'category', label: 'Spark Scala', items: [
        'foundations/language/scala/lab-scala-getting-started/README',
      ]},
    ]},
    {type: 'category', label: 'Data Storage', items: [
      {type: 'category', label: 'Flat Files', items: [
        'storage/serialization',
        'storage/csv',
        'storage/xml',
        'storage/json',
        'storage/avro',
        'storage/parquet',
        'storage/orc',
        'storage/arrow',
        'storage/hudi',
        'storage/iceberg',
        'storage/database-storage-engines',
        'storage/avro-vs-parquet-vs-orc',
        'storage/parquet-vs-csv',
        'storage/lab-data-loading-python/README',
        'storage/lab-processing-json-data/README',
      ]},
      {type: 'category', label: 'Databases', items: [
        'storage/postgres',
        'storage/mysql',
        'storage/sqlite',
        'storage/duckdb',
        'storage/gcp-cloudsql',
        'storage/azure-sql',
        'storage/interview-questions',
        'storage/postgres-vs-mysql',
        'storage/lab-aws-rds-service/README',
        'storage/lab-mysql-data-ingestion/README',
        'storage/lab-sqlite-basics/README',
        'storage/lab-postgres-getting-started/README',
        'storage/lab-postgres-bash-etl/README',
        'storage/lab-postgres-crime-reports/README',
        'storage/lab-postgres-trips-stored-procedure/README',
        'storage/lab-mysql-police-api-etl/README',
        'storage/lab-gcp-cloudsql-nyctaxi/README',
        'storage/lab-azure-sql-securing-databases/README',
        'storage/lab-db2-bookshop-petsale-data-ingestion/README',
        'storage/lab-duckdb-analytics-bank-tpch-nyctaxi/README',
        'storage/lab-sqlite-hipolabs-api/README',
        'storage/database-links',
      ]},
      {type: 'category', label: 'NoSQL Databases', items: [
        'storage/cassandra',
        'storage/gcp-bigtable',
        'storage/aws-dynamodb',
        'storage/apache-couchdb',
        'storage/mongodb',
        'storage/lab-getting-started-with-cassandra/README',
        'storage/lab-gcp-streaming-bigtable/README',
        'storage/lab-amazon-keyspaces/README',
        'storage/lab-intro-to-dynamodb/README',
        'storage/lab-mongodb-basics/README',
        'storage/lab-couchdb-movies-data-migration/README'
      ]},
      {type: 'category', label: 'Warehouses', items: [
        'storage/data-warehouses',
        'storage/athena',
        'storage/project-athena-federated/README',
        'storage/redshift',
        'storage/lab-redshift-data-loading',
        'storage/lab-redshift-data-loading-analysis',
        'storage/lab-redshift-table-design-query-tuning',
        'storage/lab-redshift-scd',
        'storage/lab-redshift-scd-2',
        'storage/lab-redshift-ongoing-load-elt',
        'storage/lab-redshift-spectrum-query-datalake',
        'storage/lab-redshift-spectrum-query-tuning',
        'storage/bigquery',
        'storage/snowflake',
        'storage/warehouse-links',
      ]},
      {type: 'category', label: 'Data Lakes', items: [
        'storage/datalakes',
        'storage/why-datalakes',
        'storage/azure-datalake',
        'storage/gcs',
        'storage/lab-datalake-healthcare-s3-glue-athena/README',
        'storage/lab-adl-create-manage-data/README',
        'storage/lab-adl-securing-monitoring-lakes/README',
      ]},
      {type: 'category', label: 'Lakehouses', items: [
        'storage/data-lakehouses',
        'storage/deltalake',
        'storage/apache-hudi',
        'storage/apache-iceberg',
        'storage/lab-read-s3-delta-in-python/README',
        'storage/lab-glue-emr-iceberg-serverless-lakehouse/README',
        'storage/lab-production-cleaning-deltalake/README',
        'storage/lab-scd-glue-delta/README',
      ]},
      {type: 'category', label: 'Data Meshes', items: [
        'storage/data-mesh-basics',
        'storage/casestudy-messflix-hypothetical',
      ]},
    ]},
    {type: 'category', label: 'Data Processing', items: [
      {type: 'category', label: 'Databricks', link: {type: 'doc', id: 'processing/databricks/README'}, items: [
        'processing/databricks/lab-cybersecurity-databricks/README',
        'processing/databricks/lab-databricks-clickstream/README',
        'processing/databricks/lab-databricks-deltalake/README',
        'processing/databricks/lab-deltalake-optimizations/README',
        'processing/databricks/lab-dlt-dbt/README',
        'processing/databricks/lab-healthcare-databricks/README',
        'processing/databricks/lab-iot-health-tracker/README',
        'processing/databricks/lab-loan-application/README',
        'processing/databricks/lab-retail-pos-databricks/README',
        'processing/databricks/lab-data-processing-azure-dbr/README',
        'processing/databricks/project-databricks-de/README',
        'processing/databricks/project-learnerbricks/README',
        'processing/databricks/project-advancedbricks/README',
        'processing/databricks/project-bedbricks/README',
        'processing/databricks/project-databricks-superset/README',
      ]},
      {type: 'category', label: 'AWS EMR', link: {type: 'doc', id: 'processing/aws-emr'}, items: [
        'processing/lab-emr-serverless/README',
      ]},
      {type: 'category', label: 'AWS Glue Studio', items: [
        'processing/lab-glue-advanced/README',
        'processing/lab-glue-deltalake-cdc-upsert/README',
        'processing/lab-glue-studio-custom-transforms/README',
        'processing/lab-glue-studio-tickets/README',
        'processing/lab-csv-to-parquet-conversion/README',
      ]},
      {type: 'category', label: 'AWS Lambda Function', link: {type: 'doc', id: 'processing/aws-lambda'}, items: [
        'processing/aws-lambda-snippets',
        'processing/lab-lambda-csv-parquet/README',
      ]},
      {type: 'category', label: 'Amazon Kinesis', link: {type: 'doc', id: 'processing/aws-kinesis'}, items: [
        'processing/lab-kinesis-apache-logs/README',
        'processing/lab-kinesis-clickstream-anomaly/README',
      ]},
      {type: 'category', label: 'Apache Beam', link: {type: 'doc', id: 'processing/apache-beam'}, items: [
        'processing/lab-getting-started-with-beam/README',
        'processing/lab-gcp-beam-mapreduce/README',
      ]},
      {type: 'category', label: 'GCP Dataflow', items: [
        'processing/lab-gcp-dataflow-pipeline',
        'processing/lab-gcp-dataflow-batch-pipeline',
        'processing/lab-gcp-dataflow-side-inputs',
        'processing/lab-gcp-dataflow-stream-pipeline',
        'processing/lab-gcp-serverless-dataflow',
        'processing/lab-dataflow-bigquery-etl',
      ]},
      {type: 'category', label: 'Ray', link: {type: 'doc', id: 'processing/ray'}, items: [
        'processing/lab-ray-core-basics/README',
        'processing/lab-ray-air-basics/README',
      ]},
      {type: 'category', label: 'GCP Dataproc', link: {type: 'doc', id: 'processing/gcp-dataproc'}, items: [
        'processing/lab-gcp-dataproc/README',
      ]},
      {type: 'category', label: 'Azure HDInsight', items: [
        'processing/lab-azure-hdinsight-simple-data-processing/README',
      ]},
      {type: 'category', label: 'Azure Synapse Analytics', link: {type: 'doc', id: 'processing/azure-synapse-analytics'}, items: [
        'processing/lab-azure-synapse-dataflows/README',
        'processing/lab-azure-synapse-data-processing/README',
        'processing/lab-azure-synapse-implementing-star-schema/README',
      ]},
      {type: 'category', label: 'GCP Dataprep', items: [
        'processing/lab-gcp-dataprep',
      ]},
      {type: 'category', label: 'GCP PubSub', link: {type: 'doc', id: 'processing/gcp-pubsub'}, items: [
        'processing/lab-gcp-pubsub',
        'processing/lab-gcp-pubsub-processing',
      ]},
      {type: 'category', label: 'Apache Kafka', link: {type: 'doc', id: 'processing/apache-kafka'}, items: [
        'processing/lab-kafka-cli/README',
        'processing/lab-kafka-python/README',
        'processing/lab-confluent-python/README',
        'processing/lab-confluent-kafka-faker/README',
        'processing/lab-kafka-fraud-detection/README',
        'processing/lab-kafka-nyctaxi/README',
        'processing/lab-kafka-python-ecs/README',
        'processing/lab-kafka-spark-streaming/README',
        'processing/lab-kafka-stock-market/README',
        'processing/lab-kafka-toll-analysis/README',
        'processing/project-kafka-ikea/README',
      ]},
      {type: 'category', label: 'Apache Flink', link: {type: 'doc', id: 'processing/apache-flink'}, items: [
        'processing/lab-flink-taxi-pricing/README',
        'processing/lab-flink-twitter-stream-processing/README',
        'processing/lab-flink-kafka-sink/README',
        'processing/lab-flink-kafka-source/README',
      ]},
      {type: 'category', label: 'dbt', link: {type: 'doc', id: 'processing/dbt'}, items: [
        'processing/lab-dbt-nyctaxi/README',
        'processing/lab-dbt-jaffle-shop/README',
        'processing/lab-dbt-knoema/README',
        'processing/lab-dbt-olist/README',
        'processing/lab-dbt-stackexchnge/README',
        'processing/lab-dbt-tickit/README',
        'processing/lab-dbt-tpch/README',
      ]},
      {type: 'category', label: 'Snowpark', link: {type: 'doc', id: 'processing/snowpark'}, items: [
        'processing/lab-snowpark-churnpark/README',
        'processing/lab-snowpark-dbtsnowpy/README',
        'processing/lab-snowpark-fifapark/README',
        'processing/lab-snowpark-jafflepark/README',
        'processing/lab-snowpark-knoema-regression/README',
      ]},
    ]},
    {type: 'category', label: 'Data Modeling', link: {type: 'generated-index'}, items: [
      {type: 'category', label: 'SQL Data Modeling', link: {type: 'doc', id: 'data-modeling/sql-data-modeling'}, items: [
        'data-modeling/inmon-vs-kimball',
        'data-modeling/data-modeling-stages',
        'data-modeling/3nf-data-modeling',
        'data-modeling/dimensional-modeling',
        'data-modeling/data-vault-modeling',
        'data-modeling/data-modeling-steps',
        'data-modeling/designing-scd',
        'data-modeling/designing-incremental-loading',
        'data-modeling/data-warehousing',
        'data-modeling/normalization-vs-denormalization',
        'data-modeling/cap-theorem',
        'data-modeling/quiz',
        'data-modeling/lab-airbnb-postgres-datamodel/README',
        'data-modeling/lab-cars-mysql-datamodel/README',
        'data-modeling/lab-dvd-rental-datamodel/README',
        'data-modeling/lab-google-playstore-datamodel/README',
        'data-modeling/lab-inegi-snowflake-datamodel/README',
        'data-modeling/lab-mysql-northwind-datamodel/README',
        'data-modeling/lab-mysql-retail-store-datamodel/README',
        'data-modeling/lab-postgres-busrapid-transit/README',
        'data-modeling/lab-postgres-elt-datamodel/README',
        'data-modeling/lab-postgres-ewallet-datamodel/README',
        'data-modeling/lab-postgres-housing-cdc-scd/README',
        'data-modeling/lab-snowflake-creditdebit-datamodel/README',
        'data-modeling/lab-sparkify-data-model-postgres/README',
      ]},
      {type: 'category', label: 'NoSQL Data Modeling', link: {type: 'doc', id: 'data-modeling/nosql-data-modeling'}, items: [
        'data-modeling/lab-cassandra-digital-music-library/README',
        'data-modeling/lab-cassandra-email-data-model/README',
        'data-modeling/lab-cassandra-hotel-reservations/README',
        'data-modeling/lab-cassandra-investment-data-model/README',
        'data-modeling/lab-cassandra-sensor-data-model/README',
        'data-modeling/lab-cassandra-shopping-cart-data-model/README',
      ]},
    ]},
    {type: 'category', label: 'Data Extraction', items: [
      {type: 'category', label: 'API', items: [
        'extraction/api/README',
      ]},
      {type: 'category', label: 'Faker', items: [
        'extraction/faker/lab-generate-data-with-faker/README',
      ]},
    ]},
    {type: 'category', label: 'Data Pipelines', items: [
      {type: 'category', label: 'Airflow', items: [
        'orchestration/airflow/README',
      ]},
      {type: 'category', label: 'Azure Data Factory', link: {type: 'doc', id: 'orchestration/azure-data-factory/README'} ,items: [
        'orchestration/azure-data-factory/lab-adf-incremental-loading/README',
        'orchestration/azure-data-factory/lab-batch-processing-solution/README',
        'orchestration/azure-data-factory/lab-data-ingestion-pipeline/README',
      ]},
      {type: 'category', label: 'GCP Cloud DataFusion', link: {type: 'doc', id: 'orchestration/datafusion/README'}, items: [
        'orchestration/datafusion/lab-datafusion-pipeline/README',
      ]},
      {type: 'category', label: 'AWS Step Functions', items: [
        'orchestration/stepfunctions/lab-stepfunction-athena-sns/README',
        'orchestration/stepfunctions/lab-stepfunction-ecomm-sqs/README',
      ]},
    ]},
    {type: 'category', label: 'Data Visualization', items: [
      {type: 'category', label: 'Flask', items: [
        'visualization/flask/README',
      ]},
      {type: 'category', label: 'Looker Studio', items: [
        'visualization/looker-studio/lab-gcp-streaming-analytics',
      ]},
      {type: 'category', label: 'Apache Superset', items: [
        'visualization/preset/README',
      ]},
      {type: 'category', label: 'Streamlit', items: [
        'visualization/streamlit/README',
      ]},
    ]},
    {type: 'category', label: 'DevOps', items: [
      {type: 'category', label: 'Basics', items: [
        'devops/README',
      ]},
      {type: 'category', label: 'Containers', items: [
        'devops/containers/README',
      ]},
      {type: 'category', label: 'Infra as Code', items: [
        'devops/iac/README',
      ]},
    ]},
    {type: 'category', label: 'Mathematics', link: {type: 'doc', id: 'mathematics/README'}, items: [
      {type: 'category', label: 'Probability', items: [
        'mathematics/probability/probability-distributions',
        'mathematics/probability/rules-of-probability',
      ]},
      {type: 'category', label: 'Statistics', items: [
        'mathematics/statistics/sampling',
      ]},
    ]},
    {type: 'category', label: 'Data Science', items: [
      {type: 'category', label: 'Basics', items: [
        'foundations/basics/origin',
        'foundations/basics/use-cases',
        'foundations/basics/deployment',
        'datascience/data-splits',
        'datascience/bias-variance-tradeoff',
        'datascience/metrics-and-evaluation',
        'datascience/data-preparation',
        'datascience/data-encoding',
        'datascience/feature-selection',
      ]},
      {type: 'category', label: 'Algorithms', items: [
        'datascience/algorithms/linear-regression',
        'datascience/algorithms/logistic-regression',
        'datascience/algorithms/decision-trees',
        'datascience/algorithms/random-forest',
        'datascience/algorithms/knn',
        'datascience/algorithms/gradient-boosting',
      ]},
      {type: 'category', label: 'Time-Series Forecasting', items: [
        'datascience/timeseries/prophet',
      ]},
      {type: 'category', label: 'Deep Learning', items: [
        'datascience/deep-learning/deep-learning-basics',
        'datascience/deep-learning/perceptron',
      ]},
      {type: 'category', label: 'MLOps', items: [
        'mlops/README',
        'mlops/code-snippets',
        'mlops/mlflow/README'
      ]},
    ]},
    {type: 'category', label: 'Extras', items: [
      {type: 'category', label: 'Case Studies', link: {type: 'generated-index'}, items: [
        'casestudies/99group',
        'casestudies/airbnb',
        'casestudies/amazon',
        'casestudies/bookingdotcom',
        'casestudies/expedia',
        'casestudies/fair',
        'casestudies/harmony',
        'casestudies/helpshift',
        'casestudies/hometogo',
        'casestudies/intuit',
        'casestudies/linkedin',
        'casestudies/myntra',
        'casestudies/outfit7',
        'casestudies/panoramic',
        'casestudies/plexure',
        'casestudies/spotify',
        'casestudies/starbucks',
        'casestudies/trivago',
        'casestudies/twilio',
        'casestudies/twitter',
        'casestudies/uber',
        'casestudies/video-stream',
        'casestudies/webshoes',
        'casestudies/woot',
      ]},
      {type: 'category', label: 'Capstones', link: {type: 'generated-index'}, items: [
        'capstones/ServerlessStreamingApp/README',
        'capstones/acled/README',
        'capstones/citibike-trip-histories/README',
        'capstones/city-pollution/README',
        'capstones/city-traffic-drone/README',
        'capstones/climate/README',
        'capstones/cloudmaze/README',
        'capstones/dbt-redshift/README',
        'capstones/digitalskola/README',
        'capstones/disaster-response/README',
        'capstones/funflix/README',
        'capstones/hmc/README',
        'capstones/kinesis-flink-beam/README',
        'capstones/kinesis-flink-etl/README',
        'capstones/kortex/README',
        'capstones/lufthansa/README',
        'capstones/movie-sentiment/README',
        'capstones/multi-touch-attribution/README',
        'capstones/recofront/README',
        'capstones/reddit/README',
        'capstones/redshield/README',
        'capstones/robust-data-pipeline/README',
        'capstones/smartcity/README',
        'capstones/sparkify/README',
        'capstones/spotify/README',
        'capstones/twitter-sentiment-glue/README',
        'capstones/us-immigration/README',
      ]},
      'interviewprep/README',
      'interviewprep/resume-buildup',
      'misc/resources',
      'misc/extras',
    ]},
  ],
};

module.exports = sidebars;
