select order_id,
    subscription_id,
    invoices_id,
    member_id,
    right(order_id, 4) as order_number,
    order_type,
    order_ts,
    order_ts as processed_ts,
    order_discounts,
    order_gross,
    order_tax,
    order_total,
    is_membership_order,
    is_gift_card_order::int::bool,
    financial_status,
    updated_ts,
    discount_code,
    discount_amount,
    discount_name,
    discount_target,
    initial_bigcommerce_order_id,
    'fixed_amount' as discount_type,
    true as replatform
from {{ ref('fact_order_rp') }}

union all

select order_id::text,
    null as subscription_id,
    null as invoices_id,
    member_id,
    order_number::text,
    order_type,
    order_ts,
    processed_ts,
    order_discounts,
    order_gross,
    order_tax,
    order_total,
    is_membership_order,
    is_gift_card_order,
    financial_status,
    updated_ts,
    discount_code,
    discount_amount,
    null as discount_name,
    null as discount_target,
    null as initial_bigcommerce_order_id,
    discount_type,
    false as replatform
from {{ref('fact_order_shopify')}}