aws s3 cp s3://wysde-assets/api/fastapi/academic-forum.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/errorHandling.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/fastapi-lakehouse.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/databricks.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/newsstand.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/tourist-system.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/piccolo.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/erp-system.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/routing.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/recipe-system.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/templating.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/fitness-club.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/auction-system.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/amazon-fresh-api.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/standard2.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/book-resale.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/planner.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/restaurant-system.zip ./
aws s3 cp s3://wysde-assets/api/fastapi/ps01-docker-fastapi.zip ./