install:
	wget https://repo.anaconda.com/archive/Anaconda3-2022.10-Linux-x86_64.sh
	bash Anaconda3-2022.10-Linux-x86_64.sh
	source ~/.bashrc
	conda create -n env python=3.9.13 anaconda
	conda activate env