def nom_entidad(entidad:int):    
 if entidad == 1: return 'AGUASCALIENTES'
 if entidad == 2: return 'BAJA CALIFORNIA'
 if entidad == 3: return 'BAJA CALIFORNIA SUR'
 if entidad == 4: return 'CAMPECHE'
 if entidad == 5: return 'COAHUILA DE ZARAGOZA'
 if entidad == 6: return 'COLIMA'
 if entidad == 7: return 'CHIAPAS'
 if entidad == 8: return 'CHIHUAHUA'
 if entidad == 9: return 'CUIDAD DE MEXICO'
 if entidad == 10: return 'DURANGO'
 if entidad == 11: return 'GUANAJUATO'
 if entidad == 12: return 'GUERRERO'
 if entidad == 13: return 'HIDALGO'
 if entidad == 14: return 'JALISCO'
 if entidad == 15: return 'MEXICO'
 if entidad == 16: return 'MICHOACAN DE OCAMPO'
 if entidad == 17: return 'MORELOS'
 if entidad == 18: return 'NAYARIT'
 if entidad == 19: return 'NUEVO LEON'
 if entidad == 20: return 'OAXACA'
 if entidad == 21: return 'PUEBLA'
 if entidad == 22: return 'QUERETARO DE ARTEAGA'
 if entidad == 23: return 'QUINTANA ROO'
 if entidad == 24: return 'SAN LUIS POTOSI'
 if entidad == 25: return 'SINALOA'
 if entidad == 26: return 'SONORA'
 if entidad == 27: return 'TABASCO'
 if entidad == 28: return 'TAMAULIPAS'
 if entidad == 29: return 'TLAXCALA'
 if entidad == 30: return 'VERACRUZ DE IGNACIO DE LA LLAVE'
 if entidad == 31: return 'YUCATAN'
 if entidad == 32: return 'ZACATECAS'